force-app/main/default/objects/ApplicationErrorLog__c/ApplicationErrorLog__c.object-meta.xml
<CustomObject>
    <description>Persistent store for Application Errors logged using the logging framework.</description>
    <label>Application Error Log</label>
    <nameField>
        <displayFormat>E-{0000000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApplicationErrorLog__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <description>Application that logged this error.</description>
    <label>Application Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationErrorLog__c/fields/Classname__c.field-meta.xml
<CustomField>
    <fullName>Classname__c</fullName>
    <description>Apex Class, Trigger, or Flow name</description>
    <label>Class Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationErrorLog__c/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <description>Execution Context</description>
    <defaultValue>&apos;Unknown&apos;</defaultValue>
    <label>Context</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Class</fullName>
            </value>
            <value>
                <fullName>Trigger</fullName>
            </value>
            <value>
                <fullName>AnonymousBlock</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ApplicationErrorLog__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>Technical Error Message</description>
    <label>Error Message</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationErrorLog__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <description>Line Number in Apex Class or Trigger</description>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ApplicationErrorLog__c/fields/MethodName__c.field-meta.xml
<CustomField>
    <fullName>MethodName__c</fullName>
    <description>Class method name or Flow Element name</description>
    <label>Method Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationErrorLog__c/fields/RelatedRecordId__c.field-meta.xml
<CustomField>
    <fullName>RelatedRecordId__c</fullName>
    <description>Salesforce RecordId of Record related to this error log.</description>
    <externalId>true</externalId>
    <label>Related Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApplicationErrorLog__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <description>Full StackTrace if related to an exception.</description>
    <label>StackTrace</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LogUtilFlowWrapper_Test.cls
@isTest
public class LogUtilFlowWrapper_Test {
    private testmethod static void testWrapper() {
        // Assumptions that are constants in the Flow itself
        final String APP='MyTestApplication';
        final String FLOWNAME='TestFlowFault';
        final String MSG='This error occurred when the flow tried to create records: REQUIRED_FIELD_MISSING:';
        final String FLOWELEMENT='CreateBadLeadRecord';
        
        Test.startTest();
        
        Flow.Interview.TestFlowFault testFlow = new Flow.Interview.TestFlowFault(new map<String,Object>());
        testFlow.start();
        
        Test.stopTest();
        
        List<ApplicationErrorLog__c> logs = [Select Id, Name
                                             , Application__c
                                             , ErrorMessage__c
                                             , Classname__c
                                             , Context__c
                                             , StackTrace__c
                                             , Methodname__c
                                             , LineNumber__c
                                             , RelatedRecordId__c 
                                            FROM ApplicationErrorLog__c];
        
        System.Assert(!logs.isEmpty(),'Expected an error to be logged');
        System.AssertEquals(APP,logs[0].Application__c);
        System.AssertEquals(FLOWNAME,logs[0].Classname__c);
        System.AssertEquals(FLOWELEMENT,logs[0].Methodname__c);
        System.AssertEquals(null,logs[0].StackTrace__c);
        System.AssertEquals('Flow',logs[0].Context__c);
        System.AssertEquals(null,logs[0].RelatedRecordId__c);
        System.Assert((''+logs[0].ErrorMessage__c).startsWith(MSG));
    }
}